# Generated by Django 4.1.5 on 2023-01-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rating_goal_alter_rating_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='brought_books',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='brought_instrument',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='progress',
        ),
    ]
