# Generated by Django 4.1.5 on 2023-02-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_lesson_behavior_remove_lesson_brought_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'school', 'user'), name='unique_courses_name_school_user'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('lesson', 'goal'), name='unique_ratings_lesson_and_goal'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_schools_name'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'school'), name='unique_students_name_school'),
        ),
    ]
