# Generated by Django 4.1.5 on 2023-02-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_course_school_id_remove_course_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
    ]
